### PR TITLE
Support Laravel 5.5 to 6.0

### PR DESCRIPTION
**Pull request by spawnia**
- Drop support for PHP 7.0, as the newer PHPUnit versions need the `: void` return type hint
- Include time measurement functionality from newer Laravel
- Pass `\Illuminate\Contracts\Events\Dispatcher` to parent constructor

### CODE REVIEW

**Comment by spawnia** [comment]
Travis seems to not run anymore, can you re-enable it?

Here is the successful test run from our fork: https://travis-ci.com/mll-lab/laravel-conditional-migrations/builds/132308824

**Comment by spawnia** [comment]
@svenluijten can you take a look?

**Comment by svenluijten** [comment]
Hi @spawnia! I'm not employed at OnlinePets anymore, so I don't have write-access to this repository. Maybe @thomasmoors or @MartijnBastiaansen can help you 🙂

**Comment by MartijnBastiaansen** [comment]
Hi @spawnia ,

We aren't maintaining this module anymore. Please feel free to pick it up and maintain it yourself, I will put this one into archive

Best regards,

Martijn

**Comment by spawnia** [comment]
Thanks, I will publish my fork, keeping a reference to and license of your package.

**Comment by spawnia** [comment]
Would you be so kind and include a reference to https://github.com/mll-lab/laravel-conditional-migrations at the top of your README? I plan to maintain this package further over there.

Thanks for the original, it has served us well.

**Comment by MartijnBastiaansen** [comment]
Added a reference at the top of the readme.

**Pull request closed without merging**
